server:
    port: 8888
    contextPath: /springboot-demo/api

spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_springboot?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=CTT&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456

mybatis:
    mapperLocations: classpath*:/mapper/**/*.xml
    typeAliasesPackage: com.gyf.demo.model

log:
    base: /u03/tbl/logs/
    level: debug
    name: springboot-demo